<?php
/**
 * @file
 * quick_links_navigation.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function quick_links_navigation_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-quick-links_career-and-leadership-courses:http://www.careers.uiowa.edu/academicprograms.html
  $menu_links['menu-quick-links_career-and-leadership-courses:http://www.careers.uiowa.edu/academicprograms.html'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://www.careers.uiowa.edu/academicprograms.html',
    'router_path' => '',
    'link_title' => 'Career and Leadership Courses',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_career-and-leadership-courses:http://www.careers.uiowa.edu/academicprograms.html',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-quick-links_career-fairs:http://www.careers.uiowa.edu/fairs
  $menu_links['menu-quick-links_career-fairs:http://www.careers.uiowa.edu/fairs'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://www.careers.uiowa.edu/fairs',
    'router_path' => '',
    'link_title' => 'Career Fairs',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_career-fairs:http://www.careers.uiowa.edu/fairs',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-quick-links_career-guide:http://www.careers.uiowa.edu/guide.html
  $menu_links['menu-quick-links_career-guide:http://www.careers.uiowa.edu/guide.html'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://www.careers.uiowa.edu/guide.html',
    'router_path' => '',
    'link_title' => 'Career Guide',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_career-guide:http://www.careers.uiowa.edu/guide.html',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-quick-links_career-leadership-academy:http://www.careers.uiowa.edu/leadershipacademy/
  $menu_links['menu-quick-links_career-leadership-academy:http://www.careers.uiowa.edu/leadershipacademy/'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://www.careers.uiowa.edu/leadershipacademy/',
    'router_path' => '',
    'link_title' => 'Career Leadership Academy',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_career-leadership-academy:http://www.careers.uiowa.edu/leadershipacademy/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-quick-links_community-based-learning-program:http://www.careers.uiowa.edu/cblp/
  $menu_links['menu-quick-links_community-based-learning-program:http://www.careers.uiowa.edu/cblp/'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://www.careers.uiowa.edu/cblp/',
    'router_path' => '',
    'link_title' => 'Community-Based Learning Program',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_community-based-learning-program:http://www.careers.uiowa.edu/cblp/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-quick-links_hireahawkcom:http://hireahawk.com
  $menu_links['menu-quick-links_hireahawkcom:http://hireahawk.com'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://hireahawk.com',
    'router_path' => '',
    'link_title' => 'HireaHawk.com',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_hireahawkcom:http://hireahawk.com',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-quick-links_internships:http://careers.uiowa.edu
  $menu_links['menu-quick-links_internships:http://careers.uiowa.edu'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://careers.uiowa.edu',
    'router_path' => '',
    'link_title' => 'Internships',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_internships:http://careers.uiowa.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-quick-links_resources-for-special-populations:http://careers.uiowa.edu
  $menu_links['menu-quick-links_resources-for-special-populations:http://careers.uiowa.edu'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://careers.uiowa.edu',
    'router_path' => '',
    'link_title' => 'Resources for Special Populations',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_resources-for-special-populations:http://careers.uiowa.edu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-quick-links_the-washington-center:http://www.careers.uiowa.edu/twc/
  $menu_links['menu-quick-links_the-washington-center:http://www.careers.uiowa.edu/twc/'] = array(
    'menu_name' => 'menu-quick-links',
    'link_path' => 'http://www.careers.uiowa.edu/twc/',
    'router_path' => '',
    'link_title' => 'The Washington Center',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-quick-links_the-washington-center:http://www.careers.uiowa.edu/twc/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Career Fairs');
  t('Career Guide');
  t('Career Leadership Academy');
  t('Career and Leadership Courses');
  t('Community-Based Learning Program');
  t('HireaHawk.com');
  t('Internships');
  t('Resources for Special Populations');
  t('The Washington Center');


  return $menu_links;
}
