<?php

/**
 * @file
 *
 * Integration for Simplicity CSM.
 */

function uiowa_csm_add_form($form, &$form_state) {
  // Get a list of all calendars available.
  $events = _uiowa_csm_get_events();

  dpm($events);

  return $form;
}

/**
 * Implements hook_default_wsclient_service().
 *
 */
function uiowa_csm_default_wsclient_service() {
  $service = new WSClientServiceDescription();
  $service->name = 'simplicity_events';
  $service->label = 'Test Events';
  $service->url = 'https://uiowa-csm.symplicity.com/ws/report_api.php?wsdl';
  $service->type = 'soap';

  try {
    $service->endpoint()->initializeMetaData();
    $services[$service->name] = $service;
  }
  catch (WSClientException $e) {
    watchdog('wsclient', $e->__toString());
  }

  return $services;
}

function uiowa_csm_service_load($services) {
  $service->settings['options'] = array(
    'login' => 'brian-hickey@uiowa.edu',
    'password' => 'testit',
  );
}

function _uiowa_csm_get_events() {
  $service = wsclient_service_load('simplicity_events');
  //dpm($service);
  //$data = $service->getReportData('1ee5733f9bd09f41cef633d78f7380b2');
  //dpm($data);
  return $service;
}
