<?php

/**
 * @file
 *
 * Integration for Simplicity CSM.
 */

// function uiowa_csm_menu() {
//   $items = array();

//   $items['admin/config/content/test'] = array(
//     'title' => 'Test',
//     'description' => 'Testing.',
//     'page callback' => 'drupal_get_form',
//     'page arguments' => array('uiowa_csm_admin_form'),
//     'access callback' => TRUE,
//     'type' => MENU_NORMAL_ITEM,
//     'menu_name' => 'management',
//     'file' => 'uiowa_csm.module',
//     'file path' => drupal_get_path('module', 'uiowa_csm'),
//   );

//   return $items;
// }

// function uiowa_csm_admin_form($form, &$form_state) {

//   _uiowa_csm_get_events();

//   $form['description'] = array(
//     '#type' => 'item',
//     '#title' => t('University of Iowa Module Package'),
//     '#markup' => '<p>This package contains various modules developed by ITS
//      Web Services.</p>',
//   );

//   return $form;
// }

// /**
//  * Implements hook_default_wsclient_service().
//  *
//  */
// function uiowa_csm_default_wsclient_service() {
//   $service = new WSClientServiceDescription();
//   $service->name = 'simplicity_events';
//   $service->label = 'Test Events';
//   $service->url = 'https://uiowa-csm.symplicity.com/ws/report_api.php?wsdl';
//   $service->type = 'soap';

//   try {
//     $service->endpoint()->initializeMetaData();
//     $services[$service->name] = $service;
//   }
//   catch (WSClientException $e) {
//     watchdog('wsclient', $e->__toString());
//   }

//   return $services;
// }

function uiowa_csm_wsclient_service_load($services) {
  foreach ($services as $service_id => &$service) {
    if ($service_id == 'simplicity_events') {
      $service->settings['options'] = array(
        'login' => 'brian-hickey@uiowa.edu',
        'password' => 'testit',
      );
      //dpm($service);
    }
  }
}

// function _uiowa_csm_get_events() {
//   $service = wsclient_service_load('simplicity_events');
//   dpm($service);
//   $data = $service->getReportDataObject('9ae76f91d9b5013d967b39750d16fa2b');
//   dpm($data);
//   //return $service;
// }
//
//

/**
* Implements hook_feeds_parser_sources_alter().
*/
function uiowa_csm_feeds_parser_sources_alter(&$sources, $content_type) {
  $sources['field_event_type'] = array(
    'name' => t('Event Type'),
    'description' => t('The type of event.'),
    'callback' => '_uiowa_csm_get_type',
  );
}

function _uiowa_csm_get_type(FeedsSource $source, FeedsParserResult $result, $key) {
  //dpm($source);
  return dpm('$result');
}


