<?php
/**
 * @file
 * Code for the Majors feature.
 */

include_once 'majors.features.inc';

// Create a variable to store the path to this module
define('MAJORS_PATH', drupal_get_path('module', 'majors'));

function majors_theme_registry_alter(&$theme_registry) {
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'careers', MAJORS_PATH);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  // A list of templates the module will provide templates for
  $hooks = array('taxonomy_term__student-organizations__student-organizations');
  foreach ($hooks as $h) {
    // Add the key 'theme paths' if it doesn't exist in this theme's registry
    if (!isset($theme_registry[$h]['theme paths'])) {
      $theme_registry[$h]['theme paths'] = array();
    }
    //Shift this module's directory to the top of the theme path list
    if(is_array($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      if ($first_element) {
        array_unshift($theme_registry[$h]['theme paths'], $first_element, MAJORS_PATH);
      } else {
        array_unshift($theme_registry[$h]['theme paths'], MAJORS_PATH);
      }
    }
  }
}