<?php
/**
 * @file
 * Code for the Careers Events feature.
 */

include_once 'careers_events.features.inc';

// Limit Date Popup to equal or greater than today.
function careers_events_date_popup_process_alter(&$element, &$form_state, &$context) {
  $element['#datepicker_options'] = array(
    'minDate' => "0",
  );
  $element['date'] = date_popup_process_date_part($element);
}

/**
 * Implements hook_form_FORMID_alter().
 */
function careers_events_form_event_node_form_alter(&$form, &$form_state, $form_id) {
  // Disable any fields that pull data in from Localist.
  // @TODO instead of being so heavy-handed, we should first check to see that
  // the node is being "controlled" by Localist.
  $form['title']['#disabled'] = TRUE;
  $form['body']['#disabled'] = TRUE;
  $form['field_event_date']['#disabled'] = TRUE;
  $form['field_event_link']['#disabled'] = TRUE;
  $form['field_event_location']['#disabled'] = TRUE;
  $form['field_event_location_latitude']['#disabled'] = TRUE;
  $form['field_event_location_longitude']['#disabled'] = TRUE;
  $form['field_event_localist_url']['#disabled'] = TRUE;
  $form['field_event_audience']['#disabled'] = TRUE;
  $form['field_event_program']['#disabled'] = TRUE;
  $form['field_event_category']['#disabled'] = TRUE;
  $form['field_event_type']['#disabled'] = TRUE;
}