<?php
/**
 * @file
 * Code for the Video feature.
 */

include_once 'video.features.inc';

function video_form_video_node_form_alter(&$form, &$form_state, $form_id) {
dpm($form);
dpm($form_state);
  $form['field_video_link']['#states'] = array(
    'invisible' => array(
       ':input[name="field_video_file[' . LANGUAGE_NONE . ']"]' => array('checked' => FALSE),
    ),
  );
  $form['field_video_screenshot']['#states'] = array(
    'invisible' => array(
       ':input[name="field_video_check[' . LANGUAGE_NONE . ']"]' => array('checked' => FALSE),
    ),
  );
  $form['field_video_file']['#states'] = array(
    'invisible' => array(
       ':input[name="field_video_check[' . LANGUAGE_NONE . ']"]' => array('checked' => TRUE),
    ),
  );
}