<?php
/**
 * @file
 * Code for the Image Styles feature.
 */

include_once 'image_styles.features.inc';

// Create a variable to store the path to this module
define('IMAGE_STYLES_PATH', drupal_get_path('module', 'image_styles'));

/**
 * Implements hook_theme_registry_alter().
 * @see https://drupal.org/node/715160
 */
function image_styles_theme_registry_alter(&$theme_registry) {
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'careers', IMAGE_STYLES_PATH);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);

  // A list of templates the module will provide templates for
  $hooks = array(
    'file__image__employer_showcase',
    'file__image__featured',
    'file__image__featured_page',
    'file__image__people_list',
    'file__image__people_node',
    'file__image__preview',
    'file__image__square',
    'file__image_square_small',     
  );
  
  foreach ($hooks as $h) {
    // Add the key 'theme paths' if it doesn't exist in this theme's registry
    if (!isset($theme_registry[$h]['theme paths'])) {
      $theme_registry[$h]['theme paths'] = array();
    }

    // Shift this module's directory to the top of the theme path list
    if(is_array($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      if ($first_element) {
        array_unshift($theme_registry[$h]['theme paths'], $first_element, IMAGE_STYLES_PATH);
      } else {
        array_unshift($theme_registry[$h]['theme paths'], IMAGE_STYLES_PATH);
      }
    }
  }
}
