<?php
/**
 * @file
 * Code for the Employers and Organizations feature.
 */

include_once 'employers_organizations.features.inc';

// Create a variable to store the path to this module
define('EMPLOYERS_ORGANIZATIONS_PATH', drupal_get_path('module', 'employers_organizations'));

/**
 * Implements hook_theme_registry_alter().
 * @see https://drupal.org/node/715160
 */
function employers_organizations_theme_registry_alter(&$theme_registry) {
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'careers', EMPLOYERS_ORGANIZATIONS_PATH);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);

  // A list of templates the module will provide templates for
  $hooks = array('file__image__employer_showcase');
  foreach ($hooks as $h) {
    // Add the key 'theme paths' if it doesn't exist in this theme's registry
    if (!isset($theme_registry[$h]['theme paths'])) {
      $theme_registry[$h]['theme paths'] = array();
    }

    //Shift this module's directory to the top of the theme path list
    if(is_array($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      if ($first_element) {
        array_unshift($theme_registry[$h]['theme paths'], $first_element, EMPLOYERS_ORGANIZATIONS_PATH);
      } else {
        array_unshift($theme_registry[$h]['theme paths'], EMPLOYERS_ORGANIZATIONS_PATH);
      }
    }
  }
}