<?php
/**
 * @file
 *
 * Code for install, update and uninstall phases.
 */

// Implements hook_enable().
function careers_feeds_mastercal_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

/**
 * Delete list(text) field field_events_category.
 */
function careers_feeds_mastercal_update_7100() {
  // Delete the base and all instances of field_events_category.
  field_delete_field('field_events_category');
}
